### ISSUE TITLE
Missing file SwaggerConfig.cs in branch upgrade/v8-latest-test-site-upgrade

### ISSUE THREAD

**Issue by mark-allott** [JcRichards1991/Our.Shield#52]
Hi Joshua,

In commit 3fee58b63ecc5bca52595a0c60077c001dbc959c, there appears to be a new file added to the Our.Shield.Swagger project, located in the App_Start folder called `SwaggerConfig.cs`. During the commit, although the project file was updated and references the file, the file itself is not present in the repo. Can you add the missing file? Here's the error from the Error List window:

|Severity|Code|Description|Project|
|---|---|---|---|
|Error|CS2001|Source file 'C:\source\repos\Our.Shield\src\Our.Shield.Swagger\App_Start\SwaggerConfig.cs' could not be found.|Our.Shield.Swagger|

Also, just so you are aware, the latest commit on that branch (7cfefd2bbaeb48719ef4c4bf44e152664394324c) has introduced a new element in the csproj files: `<langVersion>Latests</langVersion>`, which is incompatible with the official documentation - see [-langversion (C# Compiler Options) ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option). It was probably added automagically by Visual Studio to "make your life easier". However, I'm using VS2019 and it complains _a lot_ about that particular incompatible value! Enough to force me to manually remove the element completely from the csproj files to get it to attempt compilation of the projects. After doing that, it allows VS2019's default behaviour of picking the most appropriate compiler & language version based on the target framework to kick in and then try to compile everything again.

Regards,
Mark

**Comment by JcRichards1991** [comment]
Hi @mark-allott

I currently have all the apps unloaded from the solution:

![image](https://user-images.githubusercontent.com/17648147/108063983-ee725980-7053-11eb-81bf-3d9f2078870d.png)

This is because I'm currently still in the process of fixing bugs within the Core from upgrading to be compatible with umbraco v8

The file you are referring to was added by the swashbuckle nuget package when upgrading to be compatible with .net framework v4.7.2 and shouldn't be present anyways as Our.Shield.Swagger has it's own variation and doesn't require the OOTB file with swashbuckle. See https://github.com/JcRichards1991/Our.Shield/blob/upgrade/v8-latest-test-site-upgrade/src/Our.Shield.Swagger/Initialization/Register.cs - which will configure swagger with umbraco (v7 compatible, not v8 compatible yet).

In regards to the langVersion element in the *.csproj files, I'm finding the opposite effect. I am using VS2019 communty (as opposed to professional) and I'm finding when I'm using c# v8 coding, I'm unable to build certain projects within the solution due to updating some of the code to be c#v8 compatible and having the langVersion in the *.csproj file is resolving the issue for myself.

On a side note, may I ask why are you using this test branch? as Our.Shield is not close to being compatible with umbraco v8 and I'm still a way off from having a release ready due to refactoring the code base, both the c# and angularjs and in general, just making it easier to work with the code base

**Comment by mark-allott** [comment]
Hi @JcRichards1991 

Here's a little more background: I'm new to Umbraco and have been given a project that already has an Umbraco v8 site for public consumption. The client is wanting to add "protected areas" for specific member groups and ensure all content within them is accessible only to those members who have paid for their access. Therefore, I'm looking for existing packages that can help with that particular task, rather than having to roll my own (and navigate the Umbraco learning curve at the same time). I've seen some of the other packages that are available, but did see that your package offers a "scraper defense", which will certainly help with the client brief - hence the reason for me digging into the various branches, looking for what's available for Umbraco v8.

As for swashbuckle... It's not the first time I've seen packages add a default file like that and it cause a problem or two later on :smile: - just something for you to be aware of once you reload the `Our.Shield.Swagger` project and hit the same issue!

The langVersion element is an odd one - the theory states one thing; practice is obviously proving different! For me, the issue is that it's been assigned a value outside the accepted list (i.e. _Latests_  vs **latest**) and that's why VS2019 is complaining for me. If I change the value by hand in the project file, it will accept:

- `<LangVersion></LangVersion>`
- `<LangVersion>latest</LangVersion>`
- `<LangVersion>8.0</LangVersion>`
- as well as removing the element completely

And yes, apparently, Intellisense in VS2019 tells me that the correct element name is LangVersion, not langVersion, although it is happy with either 🤦 . It would be nice if it were consistent, but we deal with the hand we're dealt.

Regards,
Mark

**Comment by JcRichards1991** [comment]
Hi @mark-allott

> Here's a little more background: I'm new to Umbraco and have been given a project that already has an Umbraco v8 site for public consumption. The client is wanting to add "protected areas" for specific member groups and ensure all content within them is accessible only to those members who have paid for their access. Therefore, I'm looking for existing packages that can help with that particular task, rather than having to roll my own (and navigate the Umbraco learning curve at the same time)

Unfortunately, Our.Shield doesn't provide the functionality you'd like, however, the functionality you'd want is already OOTB with Umbraco.

If you'd where to login to umbraco, right click (or click the 3 dots) on a content node and select the Public Access menu item:
![image](https://user-images.githubusercontent.com/17648147/108102515-8be38280-7080-11eb-995d-78584c0f2996.png)
 you'll be present with the following side panel:
![image](https://user-images.githubusercontent.com/17648147/108102587-a289d980-7080-11eb-8b90-9b2b9e2d82a6.png)
Here you can either select to setup permission for a specific Member, or via the Member Groups defined in Umbraco. 99% of the time, you'll want the Group Based Protection:
![image](https://user-images.githubusercontent.com/17648147/108102816-fac0db80-7080-11eb-88cf-28bd92a159fe.png)
Then on the following step, you can select one-to-many Member Groups that will have access to this page (or descendant pages)
![image](https://user-images.githubusercontent.com/17648147/108102986-30fe5b00-7081-11eb-9e1b-e2c7bc54cee5.png)
Choose the desired Member Groups, Select the Login node for the Login Page property, I normally set the Login node as the Error Page property as well, but this could be a page that informs the Member they don't have the correct permissions to access that area of the site. Save your changes and when you try to navigate to that page, you should be rewritten to the login page if not logged in, and if logged in and part of the correct Member Group you'll be able to access the page/descendants pages.

I hope this helps you out going forward with learning Umbraco!

> I've seen some of the other packages that are available, but did see that your package offers a "scraper defence", which will certainly help with the client brief - hence the reason for me digging into the various branches, looking for what's available for Umbraco v8.

Unfortunately, the Scraper Defence app hasn't been released yet. It was on my Road Map prior to updating to be compatible with Umbraco v8 and is more than likely something that will come down the line after an Umbraco v8 compatible version. I'll be sure to add it back onto my Road Map. The Apps that were released and will be available again once a new release is out are:

- BackofficeAccess
- FrontendAccess
- MediaProtection
- Swagger
- ELMAH (keeping support for Umbraco v7, dropping support for Umbraco v8)

> As for swashbuckle... It's not the first time I've seen packages add a default file like that and it cause a problem or two later on 😄 - just something for you to be aware of once you reload the Our.Shield.Swagger project and hit the same issue!

Yes, I removed the file, but hadn't noticed I left the reference for it in the *.csproj file. I'll be sure to remove it on my next commit

> The langVersion element is an odd one - the theory states one thing; practice is obviously proving different! For me, the issue is that it's been assigned a value outside the accepted list (i.e. Latests vs latest) and that's why VS2019 is complaining for me. If I change the value by hand in the project file, it will accept:
as well as removing the element completely
And yes, apparently, Intellisense in VS2019 tells me that the correct element name is LangVersion, not langVersion, although it is happy with either 🤦 . It would be nice if it were consistent, but we deal with the hand we're dealt.

Yes, I wasn't over the moon when I added it. Going off this [MSDN article](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/configure-language-version) it does states that all .Net Framework versions supports up to c#7.3 (so I must be trying to use some v7.3 code and not v8), however, going of [this article](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/langversion-compiler-option) the default langVersion option is "latestMajor" so it would want v7.0 coding, hence the move to just stating "latest" as the value so that I can take advantage of v7.3 Just a nightmare 😒
